### ISSUE TITLE
Add data handling to Timesheet UI component 

### ISSUE THREAD

**Issue by zsagia** [zsigmondrab/time-tracking-portlet#44]
- resource request: userId, companyId, intervalEndDate, intervalStartDate
- add WorkDay remote service: userId, companyId, startTime, endTime, dayOfYearId, pause, serviceContext
- update WorkDay remote service: userId, startTime, endTime, dayOfYearId, pause, serviceContext

**Comment by zsigmondrab** [comment]
merged
